<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class FamilyEnvHealth extends Model
{
    use HasFactory;

    protected $fillable=[
        'user_id',
        'plumbing',
        'water_sources',
        'water_sources',
        'toilet',
        'sewage',
        'waste',
        'has_livestock',
        'animal_waste',
        'has_city_gas'
    ];

    public function user()
    {
        return $this->belongsTo(User::class);
    }

    public function update(array $attributes = [], array $options = [])
    {
        foreach ($this->getFillable() as $item){
            if ($item == 'user_id')
                continue;
            if (!isset($attributes[$item]))
                $attributes[$item] = 0;
        }
        return parent::update($attributes, $options); // TODO: Change the autogenerated stub
    }

}
